{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyapp.fullname" . }}-{{ .Values.api.name }}
  labels:
    {{- include "pyapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.api.name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.api.name }}
{{- end }}
